"""Regenerate LEDGER_INDEX.md from findings.tsv and results_prediction.tsv, and validate the
structured fields rule B19 requires.

`RESEARCH_LOG.md` is ~449 KB / ~5,900 lines. It was listed in the run instructions as required
reading at the start of every cycle, which is not possible at that size — so cycles read its tail and
inferred the rest. This script produces the thing that IS readable: one line per experiment, with the
fields a cycle actually needs in order to avoid repeating work.

    python3 make_index.py            # regenerate LEDGER_INDEX.md, report validation problems
    python3 make_index.py --check    # validate only, non-zero exit if a NEW row breaks B19

B19 schema (the seven fields inserted after `status`):

    design   one of the DESIGNS vocabulary below
    windows  transitions used, e.g. "2021->2024", "2014->2024", "all4", or "2024" for a cross-section
    frame    pan_dev / pan_all / pan_grp:<slice> / pan_hi / micro
    n        nominal country (or respondent) count of the headline cell
    neff     Kish effective n of that cell, or na for unweighted-only designs
    r_w      headline weighted statistic, or na
    r_u      headline unweighted twin, or na
    parent   parent experiment id, or "none" for a breadth draw

Empty cells in rows logged before 2026-08-15 mean NOT RECOVERED by the backfill, never zero.
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FINDINGS = os.path.join(HERE, "findings.tsv")
PREDICTIONS = os.path.join(HERE, "results_prediction.tsv")
INDEX = os.path.join(HERE, "LEDGER_INDEX.md")

# Rows from this experiment number onward must carry the B19 fields.
B19_FROM = 46

DESIGNS = {
    "delta-delta",        # contemporaneous change vs change, one window (B14: diagnostic only)
    "delta-delta-multi",  # the same, tested across two or more transitions
    "long-difference",    # a span of two or more transitions
    "level-cross-section",
    "level-to-change",    # lagged: level at t vs change t->t+1 (B5)
    "partial",
    "gap-trajectory",
    "distribution",       # shares of economies, per-window distributions
    "audit",              # inference / multiple-testing / replication audits over the ledger
    "measurement",        # instrument diagnostics, mapping passes, orientation screens
    "micro-cross-section",
    "prediction",
}

STATUS_ORDER = ["keep-general", "keep-general-unweighted", "keep", "keep-window",
                "keep-weighted", "keep-unweighted", "keep-exploratory",
                "inconclusive", "discard-weighted", "discard",
                # added 2026-08-17 (E49x): a mandatory mapping pass on an untouched module is
                # logged under the peek rule but asserts no claim, so it is neither a keep nor a
                # discard. `keep-exploratory` is the wrong slot for it -- that status is for a
                # finding whose answer was peeked, not for an instrument description.
                "exploratory"]


def load(path):
    with open(path, newline="") as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def expnum(rid):
    digits = "".join(c for c in rid if c.isdigit())
    return int(digits) if digits else 0


def validate(rows):
    problems = []
    required = ["design", "windows", "frame", "n", "neff", "r_w", "r_u", "parent"]
    for r in rows:
        rid = r.get("id", "")
        if not rid:
            continue
        new = r["stream"] != "micro" and expnum(rid) >= B19_FROM and rid.startswith("E")
        for f in required:
            v = (r.get(f) or "").strip()
            if new and not v:
                problems.append(f"{rid}: B19 field `{f}` is empty (use `na` or `?`, never blank)")
        d = (r.get("design") or "").strip()
        if d and d not in DESIGNS:
            problems.append(f"{rid}: design `{d}` is not in the vocabulary")
        if new and d == "delta-delta" and r["status"].startswith("keep"):
            problems.append(f"{rid}: rule B14 — a single adjacent-window delta-delta cannot be a "
                            f"keep (status `{r['status']}`)")
    return problems


def short(s, n):
    s = " ".join((s or "").split())
    return s if len(s) <= n else s[: n - 1] + "…"


def main():
    rows = [r for r in load(FINDINGS) if r.get("id")]
    preds = [r for r in load(PREDICTIONS) if r.get("commit")]
    problems = validate(rows)

    if "--check" in sys.argv:
        for p in problems:
            print("PROBLEM:", p)
        print(f"{len(rows)} rows, {len(problems)} problems")
        sys.exit(1 if problems else 0)

    keeps = [r for r in rows if r["status"].startswith("keep")]
    by_status = {}
    for r in rows:
        by_status.setdefault(r["status"], []).append(r)

    out = []
    w = out.append
    w("# Ledger index — one line per experiment\n")
    w("**Generated by `python3 make_index.py`. Do not hand-edit — edit `findings.tsv` and "
      "regenerate.**\n")
    w("This file is the required cycle read (rule: Documentation obligation 1, 2026-08-15c). "
      "`RESEARCH_LOG.md` stays the append-only record and is consulted by `grep` for one "
      "experiment at a time, never front to back.\n")
    w(f"**{len(rows)} logged experiments** · {len(keeps)} keeps · {len(preds)} prediction rows\n")

    w("## Status counts\n")
    w("| status | n |")
    w("|---|---|")
    for s in STATUS_ORDER + sorted(set(by_status) - set(STATUS_ORDER)):
        if s in by_status:
            w(f"| `{s}` | {len(by_status[s])} |")
    w("")

    w("## Design families\n")
    fam = {}
    for r in rows:
        fam.setdefault((r.get("design") or "(not backfilled)").strip() or "(not backfilled)",
                       []).append(r)
    w("| design | n | keeps |")
    w("|---|---|---|")
    for k in sorted(fam, key=lambda k: -len(fam[k])):
        w(f"| `{k}` | {len(fam[k])} | {sum(1 for r in fam[k] if r['status'].startswith('keep'))} |")
    w("")

    w("## The keeps, most-supported first\n")
    w("| id | status | design | windows | r_w / r_u | n / neff | claim |")
    w("|---|---|---|---|---|---|---|")
    keeps.sort(key=lambda r: (STATUS_ORDER.index(r["status"])
                              if r["status"] in STATUS_ORDER else 99, expnum(r["id"])))
    for r in keeps:
        rr = f"{r.get('r_w') or '—'} / {r.get('r_u') or '—'}"
        nn = f"{r.get('n') or '—'} / {r.get('neff') or '—'}"
        w(f"| `{r['id']}` | {r['status']} | {r.get('design') or '—'} | "
          f"{r.get('windows') or '—'} | {rr} | {nn} | {short(r['claim'], 120)} |")
    w("")

    w("## Every experiment, in order\n")
    w("| id | status | design | windows | frame | parent | claim |")
    w("|---|---|---|---|---|---|---|")
    for r in sorted(rows, key=lambda r: (r["stream"], expnum(r["id"]))):
        w(f"| `{r['id']}` | {r['status']} | {r.get('design') or '—'} | "
          f"{r.get('windows') or '—'} | {r.get('frame') or '—'} | {r.get('parent') or '—'} | "
          f"{short(r['claim'], 105)} |")
    w("")

    w("## Prediction stream (CLOSED at P28)\n")
    champ = {}
    for r in preds:
        if r.get("mae_pp") and r["target"] != "ALL_THREE":
            try:
                m = float(r["mae_pp"])
            except ValueError:
                continue
            if r["target"] not in champ or m < champ[r["target"]][0]:
                champ[r["target"]] = (m, r["commit"])
    w("| target | champion MAE (pp) | commit |")
    w("|---|---|---|")
    for t, (m, c) in sorted(champ.items()):
        w(f"| `{t}` | {m:.3f} | `{c}` |")
    w("")
    w("Closed by P28's rule after 28 predictor experiments. Reopening requires a change to the "
      "**task** (a new target, or an earlier holdout wave), never another mechanism on this one.\n")

    if problems:
        w("## VALIDATION PROBLEMS (rule B19)\n")
        for p in problems:
            w(f"- {p}")
        w("")

    with open(INDEX, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {INDEX}: {len(rows)} experiments, {len(keeps)} keeps, {len(problems)} problems")
    for p in problems:
        print("  PROBLEM:", p)


if __name__ == "__main__":
    main()
